<!-- module\Produit\view\produit\index\listeproduit.phtml -->

<div class="row">
	<div class="col-lg-12">
		<div class="panel">
			<div class="panel-heading">
				<div class="panel-options">
					<ul id="tabs" class="nav nav-tabs">
						<li id="tab-produit" class="active">
							<a href="#produit" title="<?php echo $this->translate('Produits'); ?>" aria-expanded="true" data-toggle="tab">
								<i class="fa fa-inbox"></i>
								<span class="hidden-xs"><?php echo $this->translate('Liste de produits'); ?></span>
							</a>
						</li>
						<li id="tab-importation-produit">
							<a href="#importation-produit" title="<?php echo $this->translate('Importer une bibliothèque de produits'); ?>" aria-expanded="false" data-toggle="tab">
								<i class="fa fa-upload"></i>
								<span class="hidden-xs"><?php echo $this->translate('Importer'); ?></span>
							</a>
						</li>
					</ul>
				</div>
				<div class="panel-body">
					<div class="tab-content">
						<!-- Panel des généralités (consultation et gestion de l'état de l'affaire) -->
						<div id="produit" class="tab-pane active">
							<div class="row">
								<a class="btn btn-primary btn-sm pull-right" href="#">
									<i class="fa fa-plus"></i>
									<?php echo $this->translate('Nouveau produit'); ?>
								</a>
								<h3><?php echo $this->translate('Rechercher un produit'); ?></h3>
							</div>
							<hr>
							<div class="row">
								<div class="col-xs-12">
									<form action="#" class="form-inline">
										<div class="form-group">
											<select name="ref_activite" id="ref_activite" class="form-control">
												<option value="">Par activité</option>
												<option value="">Fournisseur</option>
											</select>
										</div>
										<div class="form-group">
											<select name="produit_fini" id="produit_fini" class="form-control">
												<option value="">Par produit fini</option>
												<option value="">Joints</option>
												<option value="">Colle</option>
											</select>
										</div>
										<div class="form-group m-r-xs">
											<input id="mot_cle-input" class="form-control input-sm" type="search" aria-controls="table-produit" placeholder="Par mot clé" name="search">
										</div>
										<button id="search-produit" class="btn btn-white" type="submit">
											<i class="fa fa-search"></i>
											<?php echo $this->translate('Rechercher'); ?>
										</button>
									</form>
								</div>
							</div>
							<hr>
							<!-- datatable produit -->
							<div class="row">
								<div class="col-xs-12">
									<button class="btn btn-white btn-sm pull-right hidden-xs" type="submit">
										<?php echo $this->translate('Exporter'); ?>
									</button>
									<div class="form-group m-r-xs pull-right">
										<input id="produit-filter" name="produit-filter" placeholder="<?php echo $this->translate('Filtrer les résultats affichés'); ?>" type="search" class="form-control input-sm" aria-controls="table-produit">
									</div>
									
									<?php if(sizeof($this->produits)>0): ?>
									<table id="table-produit" class="table table-bordered table-hover table-striped table-condensed dataTable">
										<thead>
											<tr>
												<th><?php echo $this->translate('Code produit'); ?></th>
												<th><?php echo $this->translate('Raison sociale'); ?></th>
												<th><?php echo $this->translate('Code postale'); ?></th>
												<th><?php echo $this->translate('Ville'); ?></th>
												<th><?php echo $this->translate('Pays'); ?></th>
												<th class="actions"><?php echo $this->translate('Actions'); ?></th>
											</tr>
										</thead>
										<tfoot>
											<tr>
												<th><?php echo $this->translate('Code produit'); ?></th>
												<th><?php echo $this->translate('Raison sociale'); ?></th>
												<th><?php echo $this->translate('Code postale'); ?></th>
												<th><?php echo $this->translate('Ville'); ?></th>
												<th><?php echo $this->translate('Pays'); ?></th>
												<th class="actions"><?php echo $this->translate('Actions'); ?></th>
											</tr>
										</tfoot>
										<tbody>
											<?php foreach($this->produits as $produit): ?>
												<tr>
													<td><?php echo (isset($produit['code_client']))?$produit['code_client']:''; ?></td>
													<td><?php echo $produit['raison_sociale']; ?></td>
													<td><?php echo (isset($produit['code_postal']))?$produit['code_postal']:''; ?></td>
													<td><?php echo (isset($produit['ville']))?$produit['ville']:''; ?></td>
													<td><?php echo (isset($produit['pays']))?$produit['pays']:''; ?></td>
													<td class="actions">
                                                        <a href="<?php echo $this->url('produit/consulter_client',array('id'=>$produit['id'])); ?>"><i class="fa fa-eye fa-lg"></i></a>
                                                        <a href="<?php echo $this->url('formulaire_client',array('id'=>$produit['id'])); ?>"><i class="fa fa-pencil-square-o fa-lg"></i></a>
                                                        <a href="#" class="produit-delete-toggle produit" data-target="#produit-delete-modal" data-action="delete" data-id="<?php echo $produit['id']; ?>"><i class="fa fa-trash-o fa-lg"></i></a> 
                                                    </td>
												</tr>
											<?php endforeach; ?>
										</tbody>
									</table>
									<?php else: ?>
										<p><?php echo $this->translate('Aucune donnée n\'a été trouvée.'); ?></p>
									<?php endif; ?>
								</div>
							</div>
						</div>

						<!-- Panel de suivi de budget (gestion de l'affaire et intéractions, enregistrement de données et mise à jour) -->
						<div id="importation-produit" class="tab-pane">
							<div class="row">
								<h3><?php echo $this->translate('Importer une bibliothèque de produits'); ?></h3>
							</div>
							<hr>
							
							<div class="row">
								<div class="col-lg-12">
									<form action="#" class="horizontal-form">
										<div class="form-group">
											<label for="ref_fournisseur" class="col-lg-2 control-label">
												<?php echo $this->translate('Choix du fournisseur'); ?>
											</label>
											<div class="col-lg-10">
												<select name="ref_fournisseur" id="ref_fournisseur" class="form-control">
													<option value="">ZEPPELIN ALLEMAGNE</option>
													<option value=""></option>
												</select>
											</div>
										</div>
										<div class="form-group">
											<label for="bibliotheque" class="col-lg-2 control-label">
												<?php echo $this->translate('Depuis le fichier'); ?>
											</label>
											<div class="col-lg-10">
												<input type="text" class="form-control" placeholder="<?php echo $this->translate('Parcourir...'); ?>"> <!-- Remplacer par un dropzone -->
											</div>
										</div>
										<div class="form-group">
											<div class="col-lg-10 col-lg-offset-2">
												<button id="import-produit" class="btn btn-primary" type="submit">
													<i class="fa fa-check"></i>
													<?php echo $this->translate('Importer'); ?>
												</button>
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
