<?php

namespace DoctrineORMModule\Proxy\__CG__\Client\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class InterlocuteurClient extends \Client\Entity\InterlocuteurClient implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'id', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'nom', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'prenom', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'telephone', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'portable', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'fax', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'email', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'email2', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'dateCreationModificationFiche', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'titreCivilite', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'accepteInfos', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'envoiVersOutlook', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'refFonction', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'refSocieteClient');
        }

        return array('__isInitialized__', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'id', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'nom', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'prenom', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'telephone', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'portable', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'fax', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'email', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'email2', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'dateCreationModificationFiche', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'titreCivilite', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'accepteInfos', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'envoiVersOutlook', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'refFonction', '' . "\0" . 'Client\\Entity\\InterlocuteurClient' . "\0" . 'refSocieteClient');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (InterlocuteurClient $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomNom', array());

        return parent::getPrenomNom();
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', array());

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', array($telephone));

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPortable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPortable', array());

        return parent::getPortable();
    }

    /**
     * {@inheritDoc}
     */
    public function setPortable($portable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPortable', array($portable));

        return parent::setPortable($portable);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', array());

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', array($fax));

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail2', array());

        return parent::getEmail2();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail2($email2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail2', array($email2));

        return parent::setEmail2($email2);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreationModificationFiche()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreationModificationFiche', array());

        return parent::getDateCreationModificationFiche();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreationModificationFiche($dateCreationModificationFiche)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreationModificationFiche', array($dateCreationModificationFiche));

        return parent::setDateCreationModificationFiche($dateCreationModificationFiche);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitreCivilite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitreCivilite', array());

        return parent::getTitreCivilite();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitreCivilite($titreCivilite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitreCivilite', array($titreCivilite));

        return parent::setTitreCivilite($titreCivilite);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccepteInfos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccepteInfos', array());

        return parent::getAccepteInfos();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccepteInfos($accepteInfos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccepteInfos', array($accepteInfos));

        return parent::setAccepteInfos($accepteInfos);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnvoiVersOutlook()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnvoiVersOutlook', array());

        return parent::getEnvoiVersOutlook();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnvoiVersOutlook($envoiVersOutlook)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnvoiVersOutlook', array($envoiVersOutlook));

        return parent::setEnvoiVersOutlook($envoiVersOutlook);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefFonction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefFonction', array());

        return parent::getRefFonction();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefFonction($refFonction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefFonction', array($refFonction));

        return parent::setRefFonction($refFonction);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefSocieteClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefSocieteClient', array());

        return parent::getRefSocieteClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefSocieteClient($refSocieteClient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefSocieteClient', array($refSocieteClient));

        return parent::setRefSocieteClient($refSocieteClient);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function exchangeArray($data = array (
), $em = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exchangeArray', array($data, $em));

        return parent::exchangeArray($data, $em);
    }

    /**
     * {@inheritDoc}
     */
    public function getListeInterlocuteur($sm, $limit = 100)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListeInterlocuteur', array($sm, $limit));

        return parent::getListeInterlocuteur($sm, $limit);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterlocuteurs($sm, $critere, $limit = 100)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterlocuteurs', array($sm, $critere, $limit));

        return parent::getInterlocuteurs($sm, $critere, $limit);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomsInterlocuteurs($sm, $client = NULL, $limit = 100)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomsInterlocuteurs', array($sm, $client, $limit));

        return parent::getNomsInterlocuteurs($sm, $client, $limit);
    }

}
