<?php

namespace DoctrineORMModule\Proxy\__CG__\Client\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \Client\Entity\Client implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'codeClient', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'raisonSociale', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'dateCreation', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'effectifSalarie', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'telephone', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'fax', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'siteWeb', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'email', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'dateCreationModificationFiche', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'entrepriseALivrer', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'entrepriseAFacturer', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'numeroTva', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'numeroSiret', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'numeroApe', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'refConditionReglement', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'refModeReglement', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'refTypeSegment', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'actif', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'supprime', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'adresses', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'interlocuteurs', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'segments', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'produitsFinis');
        }

        return array('__isInitialized__', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'codeClient', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'raisonSociale', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'dateCreation', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'effectifSalarie', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'telephone', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'fax', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'siteWeb', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'email', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'dateCreationModificationFiche', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'entrepriseALivrer', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'entrepriseAFacturer', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'numeroTva', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'numeroSiret', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'numeroApe', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'refConditionReglement', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'refModeReglement', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'refTypeSegment', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'actif', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'supprime', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'adresses', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'interlocuteurs', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'segments', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'produitsFinis');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Client $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreationModificationFiche()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreationModificationFiche', array());

        return parent::getDateCreationModificationFiche();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreationModificationFiche($dateCreationModificationFiche)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreationModificationFiche', array($dateCreationModificationFiche));

        return parent::setDateCreationModificationFiche($dateCreationModificationFiche);
    }

    /**
     * {@inheritDoc}
     */
    public function getRaisonSociale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRaisonSociale', array());

        return parent::getRaisonSociale();
    }

    /**
     * {@inheritDoc}
     */
    public function setRaisonSociale($raisonSociale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRaisonSociale', array($raisonSociale));

        return parent::setRaisonSociale($raisonSociale);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeClient', array());

        return parent::getCodeClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeClient($codeClient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeClient', array($codeClient));

        return parent::setCodeClient($codeClient);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', array());

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation($dateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', array($dateCreation));

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getEffectifSalarie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEffectifSalarie', array());

        return parent::getEffectifSalarie();
    }

    /**
     * {@inheritDoc}
     */
    public function setEffectifSalarie($effectifSalarie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEffectifSalarie', array($effectifSalarie));

        return parent::setEffectifSalarie($effectifSalarie);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', array());

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', array($telephone));

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', array());

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', array($fax));

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiteWeb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiteWeb', array());

        return parent::getSiteWeb();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiteWeb($siteWeb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiteWeb', array($siteWeb));

        return parent::setSiteWeb($siteWeb);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntrepriseALivrer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntrepriseALivrer', array());

        return parent::getEntrepriseALivrer();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntrepriseALivrer($entrepriseALivrer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntrepriseALivrer', array($entrepriseALivrer));

        return parent::setEntrepriseALivrer($entrepriseALivrer);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntrepriseAFacturer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntrepriseAFacturer', array());

        return parent::getEntrepriseAFacturer();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntrepriseAFacturer($entrepriseAFacturer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntrepriseAFacturer', array($entrepriseAFacturer));

        return parent::setEntrepriseAFacturer($entrepriseAFacturer);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroTva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroTva', array());

        return parent::getNumeroTva();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroTva($numeroTva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroTva', array($numeroTva));

        return parent::setNumeroTva($numeroTva);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroSiret()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroSiret', array());

        return parent::getNumeroSiret();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroSiret($numeroSiret)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroSiret', array($numeroSiret));

        return parent::setNumeroSiret($numeroSiret);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroApe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroApe', array());

        return parent::getNumeroApe();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroApe($numeroApe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroApe', array($numeroApe));

        return parent::setNumeroApe($numeroApe);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefModeReglement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefModeReglement', array());

        return parent::getRefModeReglement();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefModeReglement($refModeReglement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefModeReglement', array($refModeReglement));

        return parent::setRefModeReglement($refModeReglement);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefConditionReglement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefConditionReglement', array());

        return parent::getRefConditionReglement();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefConditionReglement($refConditionReglement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefConditionReglement', array($refConditionReglement));

        return parent::setRefConditionReglement($refConditionReglement);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefTypeSegment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefTypeSegment', array());

        return parent::getRefTypeSegment();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefTypeSegment($refTypeSegment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefTypeSegment', array($refTypeSegment));

        return parent::setRefTypeSegment($refTypeSegment);
    }

    /**
     * {@inheritDoc}
     */
    public function getActif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActif', array());

        return parent::getActif();
    }

    /**
     * {@inheritDoc}
     */
    public function setActif($actif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActif', array($actif));

        return parent::setActif($actif);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupprime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupprime', array());

        return parent::getSupprime();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupprime($supprime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupprime', array($supprime));

        return parent::setSupprime($supprime);
    }

    /**
     * {@inheritDoc}
     */
    public function addAdresse(\Adresse\Entity\Adresse $adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAdresse', array($adresse));

        return parent::addAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAdresse(\Adresse\Entity\Adresse $adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAdresse', array($adresse));

        return parent::removeAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresses', array());

        return parent::getAdresses();
    }

    /**
     * {@inheritDoc}
     */
    public function addInterlocuteur(\Client\Entity\InterlocuteurClient $interlocuteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInterlocuteur', array($interlocuteur));

        return parent::addInterlocuteur($interlocuteur);
    }

    /**
     * {@inheritDoc}
     */
    public function removeInterlocuteur(\Client\Entity\InterlocuteurClient $interlocuteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInterlocuteur', array($interlocuteur));

        return parent::removeInterlocuteur($interlocuteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterlocuteurs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterlocuteurs', array());

        return parent::getInterlocuteurs();
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function exchangeArray($data = array (
), $em = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exchangeArray', array($data, $em));

        return parent::exchangeArray($data, $em);
    }

    /**
     * {@inheritDoc}
     */
    public function findAllClient($em = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'findAllClient', array($em));

        return parent::findAllClient($em);
    }

    /**
     * {@inheritDoc}
     */
    public function getListeClient($sm, $criteres = array (
), $limit = 100)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListeClient', array($sm, $criteres, $limit));

        return parent::getListeClient($sm, $criteres, $limit);
    }

    /**
     * {@inheritDoc}
     */
    public function getClients($sm, $critere, $limit = 100)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClients', array($sm, $critere, $limit));

        return parent::getClients($sm, $critere, $limit);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientsByProduitsFinisAndMotCle($sm, $produitsFinis, $motCle = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientsByProduitsFinisAndMotCle', array($sm, $produitsFinis, $motCle));

        return parent::getClientsByProduitsFinisAndMotCle($sm, $produitsFinis, $motCle);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientsBySegmentsAndMotCle($sm, $segments, $motCle = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientsBySegmentsAndMotCle', array($sm, $segments, $motCle));

        return parent::getClientsBySegmentsAndMotCle($sm, $segments, $motCle);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientsByTypesSegmentAndMotCle($sm, $typesSegment, $motCle = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientsByTypesSegmentAndMotCle', array($sm, $typesSegment, $motCle));

        return parent::getClientsByTypesSegmentAndMotCle($sm, $typesSegment, $motCle);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientsFromForms($sm, $codeClient = '', $raisonSociale = NULL, $limit = 100)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientsFromForms', array($sm, $codeClient, $raisonSociale, $limit));

        return parent::getClientsFromForms($sm, $codeClient, $raisonSociale, $limit);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodesClient($sm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodesClient', array($sm));

        return parent::getCodesClient($sm);
    }

    /**
     * {@inheritDoc}
     */
    public function getSegmentsId($sm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSegmentsId', array($sm));

        return parent::getSegmentsId($sm);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduitsFinisId($sm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduitsFinisId', array($sm));

        return parent::getProduitsFinisId($sm);
    }

    /**
     * {@inheritDoc}
     */
    public function addSegmentsById($sm, $arrayId = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSegmentsById', array($sm, $arrayId));

        return parent::addSegmentsById($sm, $arrayId);
    }

}
