<?php

namespace DoctrineORMModule\Proxy\__CG__\Affaire\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PosteCout extends \Affaire\Entity\PosteCout implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Affaire\\Entity\\PosteCout' . "\0" . 'id', '' . "\0" . 'Affaire\\Entity\\PosteCout' . "\0" . 'intitulePoste', '' . "\0" . 'Affaire\\Entity\\PosteCout' . "\0" . 'refCategorie');
        }

        return array('__isInitialized__', '' . "\0" . 'Affaire\\Entity\\PosteCout' . "\0" . 'id', '' . "\0" . 'Affaire\\Entity\\PosteCout' . "\0" . 'intitulePoste', '' . "\0" . 'Affaire\\Entity\\PosteCout' . "\0" . 'refCategorie');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PosteCout $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntitulePoste($intitulePoste)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntitulePoste', array($intitulePoste));

        return parent::setIntitulePoste($intitulePoste);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntitulePoste()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntitulePoste', array());

        return parent::getIntitulePoste();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefCategorie($refCategorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefCategorie', array($refCategorie));

        return parent::setRefCategorie($refCategorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefCategorie', array());

        return parent::getRefCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function getPostesCout($sm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostesCout', array($sm));

        return parent::getPostesCout($sm);
    }

}
