<?php

namespace DoctrineORMModule\Proxy\__CG__\Devis\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Devis extends \Devis\Entity\Devis implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'id', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'codeDevis', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'dateDevis', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'version', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'remise', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'fraisPort', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'delaisLivraison', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'dureeValiditePrix', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'conditionReglement', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'totalHorsPort', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'totalAvecPort', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'dateEnvoi', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'dateSignature', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'remarques', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'refPersonnel', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'refAffaire');
        }

        return array('__isInitialized__', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'id', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'codeDevis', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'dateDevis', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'version', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'remise', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'fraisPort', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'delaisLivraison', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'dureeValiditePrix', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'conditionReglement', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'totalHorsPort', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'totalAvecPort', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'dateEnvoi', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'dateSignature', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'remarques', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'refPersonnel', '' . "\0" . 'Devis\\Entity\\Devis' . "\0" . 'refAffaire');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Devis $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeDevis($codeDevis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeDevis', array($codeDevis));

        return parent::setCodeDevis($codeDevis);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeDevis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeDevis', array());

        return parent::getCodeDevis();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDevis($dateDevis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDevis', array($dateDevis));

        return parent::setDateDevis($dateDevis);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDevis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDevis', array());

        return parent::getDateDevis();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion($version)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', array($version));

        return parent::setVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', array());

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemise($remise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemise', array($remise));

        return parent::setRemise($remise);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemise', array());

        return parent::getRemise();
    }

    /**
     * {@inheritDoc}
     */
    public function setFraisPort($fraisPort)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFraisPort', array($fraisPort));

        return parent::setFraisPort($fraisPort);
    }

    /**
     * {@inheritDoc}
     */
    public function getFraisPort()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFraisPort', array());

        return parent::getFraisPort();
    }

    /**
     * {@inheritDoc}
     */
    public function setDelaisLivraison($delaisLivraison)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDelaisLivraison', array($delaisLivraison));

        return parent::setDelaisLivraison($delaisLivraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getDelaisLivraison()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDelaisLivraison', array());

        return parent::getDelaisLivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setDureeValiditePrix($dureeValiditePrix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDureeValiditePrix', array($dureeValiditePrix));

        return parent::setDureeValiditePrix($dureeValiditePrix);
    }

    /**
     * {@inheritDoc}
     */
    public function getDureeValiditePrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDureeValiditePrix', array());

        return parent::getDureeValiditePrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setConditionReglement($conditionReglement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConditionReglement', array($conditionReglement));

        return parent::setConditionReglement($conditionReglement);
    }

    /**
     * {@inheritDoc}
     */
    public function getConditionReglement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConditionReglement', array());

        return parent::getConditionReglement();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalHorsPort($totalHorsPort)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalHorsPort', array($totalHorsPort));

        return parent::setTotalHorsPort($totalHorsPort);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalHorsPort()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalHorsPort', array());

        return parent::getTotalHorsPort();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalAvecPort($totalAvecPort)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalAvecPort', array($totalAvecPort));

        return parent::setTotalAvecPort($totalAvecPort);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalAvecPort()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalAvecPort', array());

        return parent::getTotalAvecPort();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateEnvoi($dateEnvoi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateEnvoi', array($dateEnvoi));

        return parent::setDateEnvoi($dateEnvoi);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateEnvoi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateEnvoi', array());

        return parent::getDateEnvoi();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateSignature($dateSignature)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateSignature', array($dateSignature));

        return parent::setDateSignature($dateSignature);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateSignature()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateSignature', array());

        return parent::getDateSignature();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemarques($remarques)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemarques', array($remarques));

        return parent::setRemarques($remarques);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemarques()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemarques', array());

        return parent::getRemarques();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefPersonnel(\Personnel\Entity\Personnel $refPersonnel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefPersonnel', array($refPersonnel));

        return parent::setRefPersonnel($refPersonnel);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefPersonnel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefPersonnel', array());

        return parent::getRefPersonnel();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefAffaire(\Affaire\Entity\Affaire $refAffaire = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefAffaire', array($refAffaire));

        return parent::setRefAffaire($refAffaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefAffaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefAffaire', array());

        return parent::getRefAffaire();
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function exchangeArray($data = array (
), $sm = NULL, $em = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exchangeArray', array($data, $sm, $em));

        return parent::exchangeArray($data, $sm, $em);
    }

    /**
     * {@inheritDoc}
     */
    public function createNumeroVersionAuto($em)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createNumeroVersionAuto', array($em));

        return parent::createNumeroVersionAuto($em);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersionDevisMax($em, $affaire = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersionDevisMax', array($em, $affaire));

        return parent::getVersionDevisMax($em, $affaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefLignesAffaire($sm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefLignesAffaire', array($sm));

        return parent::getRefLignesAffaire($sm);
    }

    /**
     * {@inheritDoc}
     */
    public function getLignesDevis($sm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLignesDevis', array($sm));

        return parent::getLignesDevis($sm);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLigneDevis($sm, $idLigne = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLigneDevis', array($sm, $idLigne));

        return parent::removeLigneDevis($sm, $idLigne);
    }

}
