<!-- module\Client\view\client\index\consulterinterlocuteur.phtml -->

<?php

    $i=$this->interlocuteur;

    $civilite       = $i->getTitreCivilite();
    $prenom         = $i->getPrenom();
    $nom            = $i->getNom();
    $prenom         = $i->getPrenom();
    $telephone      = $i->getTelephone();
    $mobile         = $i->getPortable();
    $fax            = $i->getFax();
    $email          = $i->getEmail();
    $email2         = $i->getEmail2();
    $fonction       = $i->getRefFonction();
    $accepteInfos   = $i->getAccepteInfos();
    $envoiOutlook   = $i->getEnvoiVersOutlook();

?>
<div class="modal-header">
    <button class="close" data-dismiss="modal" type="button">
        <span aria-hidden="true">×</span>
        <span class="sr-only"><?php echo $this->translate('Fermer'); ?></span>
    </button>
    <h3>
        <strong>
            <?php echo $civilite.' '.$prenom.' '.$nom; ?>
        </strong>
        <span class="text-muted small">
            <?php echo $this->translate('Dernière modification : '); ?>
            <i class="fa fa-clock-o"></i>
            <?php echo $i->getDateCreationModificationFiche()->format('Y-m-d H:i:s'); ?>
        </span>
    </h3>
</div>
<div class="modal-body">
    
    <?php if($fonction): ?>
        <h4><?php echo $fonction->getIntituleFonction(); ?></h4>
    <?php endif; ?>

    <?php if($telephone): ?>
        <p><i class="fa fa-phone"></i> <?php echo $telephone; ?></p>
    <?php endif; ?>

    <?php if($mobile): ?>
        <p><i class="fa fa-mobile fa-lg"></i> <?php echo $mobile; ?></p>
    <?php endif; ?>

    <?php if($email): ?>
        <p><i class="fa fa-envelope"></i> <a href="mailto:<?php echo $email; ?>"><?php echo $email; ?></a></p>
    <?php endif; ?>

    <?php if($email2): ?>
        <p><i class="fa fa-envelope"></i> <a href="mailto:<?php echo $email2; ?>"><?php echo $email2; ?></a></p>
    <?php endif; ?>

    <?php if($fax): ?>
        <p><i class="fa fa-fax"></i> <?php echo $fax; ?></p>
    <?php endif; ?>                            

    <?php if($accepteInfos): ?>
        <p class="small font-bold">
            <span>
                <i class="fa fa-circle text-success"></i>
                <?php echo $this->translate('Cet interlocuteur accepte de recevoir des informations.'); ?>
            </span>
        </p>
    <?php endif; ?>

    <?php if($envoiOutlook): ?>
        <p class="small font-bold">
            <span>
                <i class="fa fa-circle text-warning"></i>
                <?php echo $this->translate('Cet interlocuteur utilise Outlook.'); ?>
            </span>
        </p>
    <?php endif; ?>
</div>