<!-- module\Analyse\view\analyse\index\index.phtml -->

<div class="row">
    <button class="btn btn-primary dim btn-large-dim" type="button"  data-placement="right" data-toggle="tooltip" data-original-title="Liste des achats">
        <i class="fa fa-eur"></i><!-- Liste des achats -->
    </button>
    <button class="btn btn-primary dim btn-large-dim" type="button"  data-placement="right" data-toggle="tooltip" data-original-title="Liste des achats">
        <i class="fa fa-line-chart"></i><!-- Liste des suivis de budget -->
    </button>
    <button class="btn btn-primary dim btn-large-dim" type="button"  data-placement="right" data-toggle="tooltip" data-original-title="Liste des achats">
        <i class="fa fa-archive"></i><!-- Liste des factures -->
    </button>
    <button class="btn btn-primary dim btn-large-dim" type="button"  data-placement="right" data-toggle="tooltip" data-original-title="Liste des achats">
        <i class="fa fa-calculator"></i><!-- Liste des règlements -->
    </button>                                
</div>
<div class="row">
    <a href="#">
        <button class="btn btn-primary dim btn-large-dim" type="button"  data-placement="right" data-toggle="tooltip" data-original-title="Liste des achats">
            <i class="fa fa-folder-open"></i><!-- Liste des devis -->
        </button>
    </a>
    <button class="btn btn-primary dim btn-large-dim" type="button"  data-placement="right" data-toggle="tooltip" data-original-title="Liste des achats">
        <i class="fa fa-shopping-cart"></i><!-- Liste des commandes -->
    </button>
    <button class="btn btn-primary dim btn-large-dim" type="button"  data-placement="right" data-toggle="tooltip" data-original-title="Liste des achats">
        <i class="fa fa-inbox"></i><!-- Liste des produits -->
    </button>
    <button class="btn btn-primary dim btn-large-dim" type="button"  data-placement="right" data-toggle="tooltip" data-original-title="Liste des achats">
        <i class="fa fa-anchor"></i><!-- Liste des projets perdus -->
    </button>
</div>