<!-- module\FicheHeure\viw\fiche-heure\index\editerficheheure.phtml -->

<div class="col-lg-12">
	<div class="ibox float-e-margins">
		<div class="ibox-title">
			<h5><?php echo $this->translate('Fiche d\'heures'); ?></h5>
			<div class="ibox-tools">
				<a href="#" class="collapse-link">
					<i class="fa fa-chevron-up"></i>
				</a>
				<a href="#" class="close-link">
					<i class="fa fa-times"></i>
				</a>
			</div>
		</div>
		<div class="ibox-content ibox-heading">
			<p><?php echo $this->translate('Consulter selon :'); ?></p>
			<form action="#" class="form-inline" role="form">
				<select name="critere" id="critere" class="form-control">
					<option value="1"><?php echo $this->translate('Personnel'); ?></option>
					<option value="2"><?php echo $this->translate('Projet'); ?></option>
				</select>
				<div class="form-group">
					
				</div>
				<button id="search-heures" class="btn btn-white" type="submit">
					<i class="fa fa-search"></i>
					<?php echo $this->translate('Rechercher'); ?>
				</button>
			</form>
		</div>
		<div class="ibox-content">
			<div class="calendar fc fc-ltr fc-unthemed"></div>
		</div>
	</div>
</div>

<div id="saisie-form-modal" class="modal inmodal in" aria-hidden="true" role="dialog" role="dialog" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button class="close" data-dismiss="modal" type="button">
					<span aria-hidden="true">×</span>
					<span class="sr-only"><?php echo $this->translate('Fermer'); ?></span>
				</button>
				<h4 class="modal-title"><?php echo $this->translate('Formulaire de saisie heures'); ?></h4>
			</div>
			<div class="modal-body">
			</div>
			<div class="modal-footer">
				<button id="annuler" class="btn btn-white" data-dismiss="modal" type="button"><i class="fa fa-times"></i> <?php echo $this->translate('Annuler'); ?></button>
				<button id="saisie-form-submit" name="submit" class="btn btn-primary pull-right" type="button" data-default-text="<?php echo $this->translate('Valider'); ?>" data-loading-text="<?php echo $this->translate('En cours...'); ?>">
					<i class="fa fa-check"></i>
					<span><?php echo $this->translate('Valider'); ?></span>
				</button>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
    var saisiesHoraires = '<?php echo $this->saisiesHoraires; ?>';
    console.log(saisiesHoraires);

    // var date = new Date();
    // var d = date.getDate();
    // var m = date.getMonth();
    // var y = date.getFullYear();
    // var saisiesHoraires = [
    //     {
    //         title: 'All Day Event',
    //         start: new Date(y, m, 1)
    //     },
    //     {
    //         title: 'Long Event',
    //         start: new Date(y, m, d-5),
    //         end: new Date(y, m, d-2),
    //     },
    //     {
    //         id: 999,
    //         title: 'Repeating Event',
    //         start: new Date(y, m, d-3, 16, 0),
    //         allDay: false,
    //     },
    //     {
    //         id: 999,
    //         title: 'Repeating Event',
    //         start: new Date(y, m, d+4, 16, 0),
    //         allDay: false
    //     },
    //     {
    //         title: 'Meeting',
    //         start: new Date(y, m, d, 10, 30),
    //         allDay: false
    //     },
    //     {
    //         title: 'Lunch',
    //         start: new Date(y, m, d, 12, 0),
    //         end: new Date(y, m, d, 14, 0),
    //         allDay: false
    //     },
    //     {
    //         title: 'Birthday Party',
    //         start: new Date(y, m, d+1, 19, 0),
    //         end: new Date(y, m, d+1, 22, 30),
    //         allDay: false
    //     },
    //     {
    //         title: 'Click for Google',
    //         start: new Date(y, m, 28),
    //         end: new Date(y, m, 29),
    //         url: 'http://google.com/'
    //     }
    // ];
</script>