<!-- module\FicheHeure\viw\fiche-heure\index\editerficheheure.phtml -->

<?php
    use Zend\Session\Container;
    $utilisateurCourant = new Container('utilisateur');
?>

<div class="col-lg-12">
	<div class="col-lg-8">
		<div class="ibox">
			<div class="ibox-title">
				<h5><?php echo $this->translate('Fiche d\'heures'); ?></h5>
				<div class="ibox-tools">
					<a href="#" class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a href="#" class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
			</div>
			<div class="ibox-content ibox-heading">
				<form action="<?php echo $this->url('editer_fiche_heures'); ?>" class="form-inline" method="get" role="form">
					<!-- <p> -->
						<?php echo $this->translate('Consulter selon : '); ?>
						<label class="radio-inline">
							<input id="option-personnel" type="radio" value="personnel" name="critere[]" <?php echo ($this->critere[0] == 'personnel') ? 'checked': ''; ?>>
							<?php echo $this->translate('Personnel'); ?>
						</label>
						<label class="radio-inline">
							<input id="option-projet" type="radio" value="projet" name="critere[]" <?php echo ($this->critere[0] == 'projet') ? 'checked': ''; ?>>
							<?php echo $this->translate('Projet'); ?>
						</label>
					<!-- </p> -->
					<!-- <div class="form-inline"> -->
						<div class="form-group">
							<select name="ref_personnel" id="ref_personnel" class="form-control">
								<option value=""><?php echo $this->translate('Personnel'); ?></option>
								<?php foreach($personnels as $personnel) : ?>
									<option value="<?php echo $personnel['id']; ?>" <?php if($personnel['id'] == $this->idPersonnel) { echo 'selected="selected"' ;} ?>><?php echo $personnel['nom_complet']; ?></option>
								<?php endforeach; ?>
							</select>
						</div>
						<div class="form-group">
							<input type="hidden" name="ref_affaire" id="ref_affaire" value="<?php echo $this->refAffaire; ?>">
							<label class="sr-only" for="numero_affaire"><?php echo $this->translate('Numéro affaire'); ?></label>
							<input name="numero_affaire" id="numero_affaire" class="form-control" type="text" placeholder="<?php echo $this->translate('Entrez un numéro de projet...'); ?>" value="<?php echo $this->numeroAffaire; ?>">
						</div>
						<button id="search-heures" class="btn btn-white" type="submit">
							<i class="fa fa-search"></i>
							<?php echo $this->translate('Rechercher'); ?>
						</button>
					<!-- </div> -->
				</form>
			</div>
			<div class="ibox-content">
				<button class="btn btn-white btn-sm pull-right hidden-xs" type="submit">
					<i class="fa fa-share"></i>
					<?php echo $this->translate('Exporter'); ?>
				</button>
				<div class="calendar fc fc-ltr fc-unthemed"></div>
			</div>
		</div>
	</div>
	<div class="col-lg-4">
		<div class="ibox">
			<div class="ibox-title">
				<h5><?php echo $this->translate('Récapitulatifs heures'); ?></h5>
				<div class="ibox-tools">
					<a href="#" class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a href="#" class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
			</div>
			<div class="ibox-content">
				<?php 
					if($this->critere[0] == 'personnel') 
					{
						echo $this->render('fiche_heure/recapitulatif-personnel');
					}
					else
					{
						echo $this->render('fiche_heure/recapitulatif-projet');
					}
				?>
			</div>
		</div>
	</div>
	
</div>

<!-- Pour editer les HORAIRES & les SAISIES PAR PROJET -->
<div id="saisie-form-modal" class="modal modal-heure inmodal in" aria-hidden="true" role="dialog" role="dialog" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button class="close" data-dismiss="modal" type="button">
					<span aria-hidden="true">×</span>
					<span class="sr-only"><?php echo $this->translate('Fermer'); ?></span>
				</button>
				<h4 class="modal-title"><?php echo $this->translate('Formulaire de saisie heures'); ?></h4>
			</div>
			<div class="modal-body">
			</div>
			<div class="modal-footer">
				<button id="annuler" class="btn btn-white" data-dismiss="modal" type="button"><i class="fa fa-times"></i> <?php echo $this->translate('Annuler'); ?></button>
				<button id="saisie-form-submit" name="submit" class="btn btn-primary pull-right" type="button" data-default-text="<?php echo $this->translate('Valider'); ?>" data-loading-text="<?php echo $this->translate('En cours...'); ?>">
					<i class="fa fa-check"></i>
					<span><?php echo $this->translate('Valider'); ?></span>
				</button>
			</div>
		</div>
	</div>
</div>

<!-- Pour editer les SAISIES PAR PROJET -->
<div id="projet-form-modal" class="modal modal-heure inmodal in" aria-hidden="true" role="dialog" role="dialog" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button class="close" data-dismiss="modal" type="button">
					<span aria-hidden="true">×</span>
					<span class="sr-only"><?php echo $this->translate('Fermer'); ?></span>
				</button>
				<h4 class="modal-title"><?php echo $this->translate('Formulaire de saisie heures'); ?></h4>
			</div>
			<div class="modal-body">
			</div>
			<div class="modal-footer">
				<button id="projet-delete-submit" class="btn btn-danger pull-left" data-loading-text="En cours..." data-default-text="<?php echo $this->translate('Supprimer'); ?>" type="button" name="submit">
					<i class="fa fa-trash"></i>
					<?php echo $this->translate('Supprimer'); ?>
				</button>
				<button id="annuler" class="btn btn-white" data-dismiss="modal" type="button"><i class="fa fa-times"></i> <?php echo $this->translate('Annuler'); ?></button>
				<button id="projet-form-submit" name="submit" class="btn btn-primary pull-right" type="button" data-default-text="<?php echo $this->translate('Valider'); ?>" data-loading-text="<?php echo $this->translate('En cours...'); ?>">
					<i class="fa fa-check"></i>
					<span><?php echo $this->translate('Valider'); ?></span>
				</button>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
    var saisiesJson = <?php echo $this->saisiesJson; ?>;
    // console.log(saisiesJson);
</script>