<div class="col-lg-12">
	<div class="ibox float-e-margins">
		<div class="ibox-title">
			<h5><?php echo $this->translate('Fiche d\'heures'); ?></h5>
			<div class="ibox-tools">
				<a href="#" class="collapse-link">
					<i class="fa fa-chevron-up"></i>
				</a>
				<a href="#" class="close-link">
					<i class="fa fa-times"></i>
				</a>
			</div>
		</div>
		<div class="ibox-content ibox-heading">
			<p><?php echo $this->translate('Consulter selon :'); ?></p>
			<form action="#" class="form-inline" role="form">
				<select name="critere" id="critere" class="form-control">
					<option value="1"><?php echo $this->translate('Personnel'); ?></option>
					<option value="2"><?php echo $this->translate('Projet'); ?></option>
				</select>
				<div class="form-group">
					
				</div>
				<button id="search-heures" class="btn btn-white" type="submit">
					<i class="fa fa-search"></i>
					<?php echo $this->translate('Rechercher'); ?>
				</button>
			</form>
		</div>
		<div class="ibox-content">
			<div class="calendar fc fc-ltr fc-unthemed"></div>
		</div>
	</div>
</div>

<?php
	// Modal avec formulaire de saisie d'heures
	echo $this->render('fiche_heure/formulairesaisieheure'); 
?>