
<!-- module\FicheHeure\view\fiche-heure\index\formulairesaisieheure.phtml -->

<div id="saisie-form-modal" class="modal inmodal in" aria-hidden="true" role="dialog" role="dialog" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button class="close" data-dismiss="modal" type="button">
					<span aria-hidden="true">×</span>
					<span class="sr-only"><?php echo $this->translate('Fermer'); ?></span>
				</button>
				<h4 class="modal-title"><?php echo $this->translate('Formulaire de saisie heures'); ?></h4>
			</div>
			<div class="modal-body">
				<p>
					<?php echo $this->translate('hello world'); ?>
					<!-- form ici -->
				</p>
			</div>
			<div class="modal-footer">
				<button id="annuler" class="btn btn-white" data-dismiss="modal" type="button"><i class="fa fa-times"></i> <?php echo $this->translate('Annuler'); ?></button>
				<button id="saisie-form-submit" name="submit" class="btn btn-primary pull-right" type="button" data-default-text="<?php echo $this->translate('Valider'); ?>" data-loading-text="<?php echo $this->translate('En cours...'); ?>">
					<i class="fa fa-check"></i>
					<span><?php echo $this->translate('Valider'); ?></span>
				</button>
			</div>
		</div>
	</div>
</div>