<table class="table table-striped">
	<thead>
		<tr>
			<th><?php echo $this->translate('Projets'); ?></th>
			<th><?php echo $this->translate('Temps prévu'); ?></th>
			<th><?php echo $this->translate('Temps passé'); ?></th>
		</tr>
	</thead>
	<tbody>
		<!-- boucle ici sur les projets -->
	</tbody>
	<tfoot>
		<tr>
			<th><?php echo $this->translate('Total heures'); ?></th>
			<th></th>
			<th></th>
		</tr>
	</tfoot>
</table>