<!-- module\Client\view\modal\overlay-confirmation-suppression-client.phtml -->

<div id="client-delete-modal" class="modal inmodal in" aria-hidden="true" role="dialog" role="dialog" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button class="close" data-dismiss="modal" type="button">
					<span aria-hidden="true">×</span>
					<span class="sr-only"><?php echo $this->translate('Fermer'); ?></span>
				</button>
				<h4 class="modal-title"><?php echo $this->translate('Confirmation de suppression'); ?></h4>
			</div>
			<div class="modal-body">
				<p><?php echo $this->translate('Êtes-vous bien certain de vouloir supprimer ce client ?'); ?></p>
				<div class="text-center"><strong id="infos-client"></strong></div>
				<p class="alert alert-danger">
					<i class="fa fa-exclamation-circle"></i>
					<?php echo $this->translate('Cette action supprimera définitivement le client ainsi que tous ses interlocuteurs.'); ?>
				</p>
			</div>
			<div class="modal-footer">
				<button id="annuler" class="btn btn-white" data-dismiss="modal" type="button"><i class="fa fa-times"></i> <?php echo $this->translate('Annuler'); ?></button>
				<button id="client-delete-submit" name="submit" class="btn btn-danger pull-right" type="button" data-default-text="<?php echo $this->translate('Supprimer'); ?>" data-loading-text="<?php echo $this->translate('En cours...'); ?>">
					<i class="fa fa-trash"></i>
					<?php echo $this->translate('Supprimer'); ?>
				</button>
			</div>
		</div>
	</div>
</div>