<!-- module\Client\view\layout\login_layout.phtml -->

<?php
    use Zend\Session\Container;
    $utilisateurCourant=new Container('utilisateur');
    $flashArray = array('errors'=>array(),'success'=>array());
    echo $this->doctype(); // <!DOCTYPE html>
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Sigma 2.0 | '.$this->layout()->headTitle))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php 

            if(!isset($this->plugins))
            {
                $this->plugins=array();
            }

            $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() .'/img/index.png'))
                 ->appendStylesheet($this->basePath('css/Inspinia/bootstrap.min.css')) // Bootstrap 
                 ->appendStylesheet($this->basePath('css/font-awesome/css/font-awesome.min.css')) // Font Awesome 4.3.0
                 ->appendStylesheet($this->basePath('css/Inspinia/animate.css'))
                 ->appendStylesheet($this->basePath('css/Inspinia/style.css'))
                 ->appendStylesheet($this->basePath('css/sigma.css'))
            ;

            echo $this->headLink();
        ?>
    </head>
    <body class="gray-bg">
		<div class="loginColumns animated fadeInDown">
            
            <div class="row">
                <div class="col-md-6">
                    <h2 class="font-bold"><?php echo $this->translate('Bienvenue sur Sigma'); ?> &#931;+</h2>
                    <p><?php echo $this->translate('Application de gestion commerciale de Zeppelin Systems France'); ?></p>
                    <h1 class="logo-name text-center visible-md visible-lg">&#931;+</h1>
                </div>
                <div class="col-md-6">
                    <?php echo $this->content; ?>
                    <p id="langage" class="text-right">
                         <a href="?lang=fr_FR"><?php echo $this->translate('Français'); ?></a> | <a href="?lang=en_US"><?php echo $this->translate('Anglais'); ?></a> 
                    </p>
                </div>
            </div>
			<hr>
            <div class="row">
                <div class="text-right"><small>&copy; 2015<?php echo (date('Y')!='2015') ? ' - '.date('Y') : ''; ?></small></div>
                <span class="hidden-xs">Copyright <a href="http://www.zeppelin-systems-france.fr/">Zeppelin Systems France SARL</a>. <?php echo $this->translate('Tous droits réservés.'); ?></span>
            </div>
		</div>

        <!-- Scripts -->

        <script type="text/javascript">
            var _module='<?php echo $this->module; ?>';
            var _action='<?php echo $this->action; ?>';
            var locale='<?php echo $utilisateurCourant->offsetGet('lang'); ?>';
        </script>

        <?php
            $this->headScript()
                ->appendFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
                ->appendFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->appendFile($this->basePath('js/jquery.min.js'))
                ->appendFile($this->basePath('js/Inspinia/bootstrap.min.js'))
                ->appendFile($this->basePath('js/Inspinia/plugins/metisMenu/jquery.metisMenu.js'))
                ->appendFile($this->basePath('js/Inspinia/plugins/slimscroll/jquery.slimscroll.min.js'))
                ->appendFile($this->basePath('js/Inspinia/inspinia.js'))
                ->appendFile($this->basePath('js/Inspinia/plugins/pace/pace.min.js'))
                ->appendFile($this->basePath('js/sigma.js'))
            ;

            echo $this->headScript();
            
            echo $this->inlineScript();
        ?> 

    </body>
</html>