<!-- module\Affaire\view\affaire\index\consulteraffaire.phtml -->

<?php
    use Zend\Session\Container;
    $utilisateurCourant = new Container('utilisateur');
    $admin = $utilisateurCourant->offsetGet('admin');
    $fonction = $utilisateurCourant->offsetGet('fonction');
?>

<?php 
    $affaire 		= $this->affaire;
    // $interlocuteurs = $client->getInterlocuteurs();
    // $adresses       = $client->getAdresses();
    // $segments       = $client->getSegments();
    // $produits       = $client->getProduitsFinis();
?>

<div class="row">
	<div class="col-lg-12">
		<div class="panel">
			<div class="panel-heading">
				<div class="panel-options">
					<ul id="tabs" class="nav nav-tabs">
						<li id="tab-generalites" class="active">
							<a href="#generalites" title="<?php echo $this->translate('Généralités'); ?>" aria-expanded="true" data-toggle="tab">
								<i class="fa fa-clipboard"></i>
								<span class="hidden-xs"><?php echo $this->translate('Généralités'); ?></span>
							</a>
						</li>
						<li id="tab-liste-produit">
							<a href="#liste-produit" title="<?php echo $this->translate('Liste de produits'); ?>" aria-expanded="false" data-toggle="tab">
								<i class="fa fa-list-ul"></i>
								<span class="hidden-xs"><?php echo $this->translate('Liste des produits'); ?></span>
							</a>
						</li>
						<!-- faire apparaitre les liens suivants que si l'affaire a son suivi de budget activé -->
						<li id="tab-suivi-budget">
							<a href="#suivi-budget" title="<?php echo $this->translate('Suivi de budget'); ?>" aria-expanded="false" data-toggle="tab">
								<i class="fa fa-table"></i>
								<span class="hidden-xs"><?php echo $this->translate('Suivi de budget'); ?></span>
							</a>
						</li>
						<li id="tab-bilan">
							<a href="#bilan" title="<?php echo $this->translate('Bilan'); ?>" aria-expanded="false" data-toggle="tab">
								<i class="fa fa-area-chart"></i>
								<span class="hidden-xs"><?php echo $this->translate('Bilan'); ?></span>
							</a>
						</li>
					</ul>
				</div>
				<div class="panel-body">
					<div class="tab-content">
						<!-- Panel des généralités (consultation et gestion de l'état de l'affaire) -->
						<div id="generalites" class="tab-pane active">
							<div class="row">
							 	<span class="text-muted small pull-right">
				                    <?php echo $this->translate('Dernière modification'); ?>
				                    <i class="fa fa-clmock-o"></i>
				                    <?php echo date('d/m/Y H:m:s',$affaire->getDateCreationModificationFiche()); ?>
				                    <!-- 30/06/2015 -->
				                </span>
				                <h3>
				                	<?php echo $affaire->getDesignationAffaire(); ?>
				                	[<?php echo $affaire->getNumeroAffaire(); ?>]
				                	<!-- Pétrin continu ligne Mikado [A13-1234] -->
				                </h3>
				                <a href="<?php echo $this->url('formulaire_affaire',array('id'=>$this->id)); ?>" class="btn btn-primary btn-xs">
				                	<i class="fa fa-pencil"></i>
				                	<!-- <a href="<?php echo $this->url('formulaire_affaire',array('id'=>$this->id)); ?>"> -->
				                		<?php echo $this->translate('Modifier l\'affaire'); ?>
				                	<!-- </a> -->
				                </a>
				                <hr class="tiny-hr">
								<div class="row">
									<div class="col-md-4 col-sm-7 b-r">
				                		<h4><?php echo $this->translate('Informations générales'); ?></h4>
				                		<p><?php echo $this->translate('Créée le').' '.date('d/m/Y',$affaire->getDateDebut()); ?></p>
				                		<ul class="list-group clear-list m-t">
											<li class="list-group-item fist-item">
												<span class="pull-right"> <?php echo $affaire->getDesignationAffaire(); ?> </span>
												<!-- <span class="label label-info">1</span> -->
												<strong><?php echo $this->translate('Nom affaire'); ?></strong>
											</li>
											<li class="list-group-item">
												<span class="pull-right"> <?php echo $this->translate($affaire->getRefCentreProfit()->getIntituleCentre()); ?> [<?php echo $this->translate($affaire->getRefCentreProfit()->getNumero()); ?>] </span>
												<!-- <span class="label label-success">2</span> -->
												<strong><?php echo $this->translate('Centre de profit'); ?></strong>
											</li>
											<li class="list-group-item">
												<span class="pull-right"> 
													<?php echo $affaire->getRefClient()->getRaisonSociale(); ?>
													<?php if($this->adresse) : ?>
														(<?php echo $this->adresse->getVille(); ?>)
													<?php endif; ?>
												</span>
												<!-- <span class="label label-primary">4</span> -->
												<strong><?php echo $this->translate('Client'); ?></strong>
											</li>
											<li class="list-group-item">
												<span class="pull-right"><?php echo ($affaire->getRefConditionReglement()) ? $this->translate($affaire->getRefConditionReglement()->getIntituleConditionReglement()) : ''; ?></span>
												<!-- <span class="label label-default">5</span> -->
												<strong><?php echo $this->translate('Conditions de règlement'); ?></strong>
											</li>
											<li class="list-group-item">
												<span class="pull-right"><?php echo ($affaire->getReferenceCommandeClient()) ? $this->translate($affaire->getReferenceCommandeClient()) : ''; ?></span>
												<!-- <span class="label label-default">5</span> -->
												<strong><?php echo $this->translate('Référence commande client'); ?></strong>
											</li>
											<li class="list-group-item">
												<span class="pull-right"><?php echo ($affaire->getReferenceDemandePrix()) ? $this->translate($affaire->getReferenceDemandePrix()) : ''; ?></span>
												<!-- <span class="label label-default">5</span> -->
												<strong><?php echo $this->translate('Référence demande de prix'); ?></strong>
											</li>
											<!-- <li class="list-group-item">
												<span class="pull-right"> 20 % à la commande </span>
												<span class="label label-primary">6</span>
												<strong><?php //echo $this->translate('Mode de règlement'); ?></strong>
											</li> -->
										</ul>
				                	</div>
				                	<div class="col-md-4 col-sm-5 b-r">
				                		<h4><?php echo $this->translate('Chargé d\'affaire'); ?></h4>
				                		<div class="widget gray-bg">
				                			<h3>
				                				<?php echo $affaire->getRefPersonnel()->getPrenomNom(); ?>
				                				<?php if($admin) : ?>
				                					<a href="#"><i class="fa fa-pencil"></i></a>
				                				<?php endif; ?>
				                			</h3>
				                		</div>
										<h4><?php echo $this->translate('Interlocuteur client'); ?></h4>
										<?php 
											if($affaire->getRefInterlocuteur()) 
											{ 
												$interlocuteur = $affaire->getRefInterlocuteur();
										?>
					                		<div class="widget gray-bg">
					                			<h3>
					                				<?php echo $interlocuteur->getPrenomNom(); ?>
					                				<a class="interlocuteur-form-toggle interlocuteur" data-id="<?php echo $interlocuteur->getId(); ?>" data-action="edit" data-target="#interlocuteur-form-modal" href="#">
					                					<i class="fa fa-pencil"></i>
					                				</a>
					                			</h3>
					                			<p class="text-uppercase"><?php echo $affaire->getRefClient()->getRaisonSociale(); ?></p>
					                			<?php if($interlocuteur->getRefFonction()) : ?>
						                			<p><?php echo $this->translate($interlocuteur->getRefFonction()->getIntituleFonction()); ?></p>
						                		<?php endif; ?>
					                			<ul class="list-unstyled m-t-md">
					                				<?php if($interlocuteur->getEmail()) : ?>
					                				<li>
					                					<span class="fa fa-envelope m-r-xs"></span>
					                					<label><?php echo $this->translate('Email'); ?> :</label>
					                					<?php echo $interlocuteur->getEmail(); ?>
					                				</li>
					                				<?php endif; ?>
					                				<?php if($interlocuteur->getEmail2()) : ?>
					                				<li>
					                					<span class="fa fa-envelope m-r-xs"></span>
					                					<label><?php echo $this->translate('Email2'); ?> :</label>
					                					<?php echo $interlocuteur->getEmail2(); ?>
					                				</li>
					                				<?php endif; ?>
					                				<?php if($interlocuteur->getFax()) : ?>
					                				<li>
					                					<span class="fa fa-fax m-r-xs"></span>
					                					<label><?php echo $this->translate('Fax'); ?> :</label>
					                					<?php echo $interlocuteur->getFax(); ?>
					                				</li>
					                				<?php endif; ?>
					                				<?php if($interlocuteur->getPortable()) : ?>
					                				<li>
					                					<span class="fa fa-mobile m-r-xs"></span>
					                					<label><?php echo $this->translate('Mobile'); ?> :</label>
					                					<?php echo $interlocuteur->getPortable(); ?>
					                				</li>
					                				<?php endif; ?>
					                				<?php if($interlocuteur->getTelephone()) : ?>
					                				<li>
					                					<span class="fa fa-mobile m-r-xs"></span>
					                					<label><?php echo $this->translate('Téléphone'); ?> :</label>
					                					<?php echo $interlocuteur->getTelephone(); ?>
					                				</li>
					                				<?php endif; ?>
					                			</ul>
					                		</div>
					                	<?php 
					                		} else { 
					                	?>
					                		<?php echo $this->translate('Aucun interlocuteur pour cette affaire.'); ?>
					                	<?php } ?>
				                	</div>
				                	<div class="col-md-4 col-sm-12">
				                		<div class="pull-right dropdown">
				                			<button class="dropdown-toggle btn-white" data-toggle="dropdown">
				                				<i class="fa fa-angle-down"></i>
				                			</button>
				                			<ul class="dropdown-menu">
				                				<li><a href="#"><?php echo $this->translate('Mettre à jour l\'état'); ?></a></li>
				                			</ul>
				                		</div>
				                		<h4><?php echo $this->translate('Historique'); ?></h4>
										<?php echo $this->render('affaire/historique'); ?>
				                	</div>
				                </div>
							</div>
							
							<div class="row" style="margin-top:20px">
								<a  href="#" class="pull-right">
									<i class="fa fa-server"></i>
				                    <?php echo $this->translate('Voir sur serveur'); ?>
				                </a>
								<h3><?php echo $this->translate('Documents de gestion'); ?></h3>
				            	<hr>
								<div class="col-lg-6">
									<?php echo $this->render('affaire/listedevis'); ?>
									<?php echo $this->render('affaire/listefacture'); ?>
									<?php echo $this->render('affaire/listeconfirmation'); ?>									
								</div>
								<div class="col-lg-6">
									<?php echo $this->render('affaire/listecommande'); ?>
									<?php echo $this->render('affaire/listebordereau'); ?>
								</div>
							</div>
						</div>

						<!-- Panel de suivi de budget (gestion de l'affaire et intéractions, enregistrement de données et mise à jour) -->
						<div id="liste-produit" class="tab-pane">

							<!-- A modifier de sorte à ce que la liste soit générée en AJAX au clic sur l'onglet -->
							<?php echo $this->render('affaire/listeproduit'); ?>
						</div>

						<!-- Panel de suivi de budget -->
						<div id="suivi-budget" class="tab-pane">
							<div class="row">

								<h3><?php echo $this->translate('Suivi de budget'); ?></h3>
							</div>
							<hr>
							<div class="col-lg-12">
								<?php if(!$affaire->getSuiviBudgetActif()) : ?>
									<button class="btn btn-primary btn-md"><?php echo $this->translate('Activer le suivi de budget'); ?></button>
								<?php endif; ?>
							</div>
						</div>

						<!-- Panel du Bilan des budgets -->
						<div id="bilan" class="tab-pane">
							<div class="row">
								<h3><?php echo $this->translate('Bilan'); ?></h3>
							</div>
							<hr>
							<div class="col-lg-12">
								<!-- Morris Line Chart -->
								<div id="morris-line-chart" style="height:250px;"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<?php	
	echo $this->render('personnel/overlay_formulaire_personnel');
	echo $this->render('client/overlay_formulaire_interlocuteur');
?>
