<div id="vertical-timeline" class="scrollable vertical-container dark-timeline">
	<p class="etat-courant">En attente des envois de commandes</p>
	<!--<p class="autre-etat">En attente de facturation<br><s>En attente de commande fournisseur</s></p>-->
	<div class="vertical-timeline-block">
		<div class="vertical-timeline-icon navy-bg">
			<i class="fa fa-check"></i>
		</div>
		<div class="vertical-timeline-content">
			<strong>Affaire signée</strong>
			<p>
				<i class="fa fa-paperclip"></i>
				Devis n°<a href="">13-1234-2</a>
			</p>
			<p class="small text-muted">
				<i class="fa fa-clock-o"></i>
				03/07/2015
			</p>
		</div>
	</div>
	<p class="autre-etat"><s>En attente de réponse client</s></p>
	<div class="vertical-timeline-block">
		<div class="vertical-timeline-icon gray-bg">
			<i class="fa fa-envelope"></i>
		</div>
		<div class="vertical-timeline-content">
			<strong>Devis envoyé(s)</strong>
			<p>
				<i class="fa fa-paperclip"></i>
				Devis n°<a href="">13-1234-1</a>
			<br>
				<i class="fa fa-paperclip"></i>
				Devis n°<a href="">13-1234-2</a>
			</p>
			<p class="small text-muted">
				<i class="fa fa-clock-o"></i>
				01/07/2015
			</p>
		</div>
	</div>
	<p class="autre-etat"><s>En attente des envois de devis</s></p>
	<div class="vertical-timeline-block">
		<div class="vertical-timeline-icon gray-bg">
			<i class="fa fa-flag"></i>
		</div>
		<div class="vertical-timeline-content">
			<strong>Affaire créée</strong>
			<p class="small text-muted">
				<i class="fa fa-clock-o"></i>
				10/06/2015
			</p>
		</div>
	</div>
</div>