<div class="row">
	<div class="col-lg-12">
		<div class="table-responsive">
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>
							<?php echo $this->translate('Remise'); ?>
						</th>
						<th>
							<?php echo $this->translate('Frais de port'); ?>
						</th>
						<th>
							<?php echo $this->translate('Référence demande de prix'); ?>
						</th>
						<th>
							<?php echo $this->translate('Référence commande client'); ?>
						</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>
							<?php echo number_format($affaire->getRemise(),2,',',' '); ?>
							€
						</td>
						<td>
							<?php echo number_format($affaire->getFraisPort(),2,',',' '); ?>
							€
						</td>
						<td>
							<?php echo (!empty($affaire->getReferenceDemandePrix())) ? $affaire->getReferenceDemandePrix() : ''; ?>
						</td>
						<td>
							<?php echo (!empty($affaire->getReferenceCommandeClient())) ? $affaire->getReferenceCommandeClient() : ''; ?>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
		

		

		<div class="row">
			<div class="col-lg-2">
				<button class="btn btn-primary btn-sm">
					<i class="fa fa-plus"></i>
					<?php echo $this->translate('Ligne affaire'); ?>
				</button>
			</div>
			<div class="col-sm-6">
				<!-- <input id="filter" class="form-control input-sm m-b-xs" type="text" placeholder="<?php echo $this->translate('Rechercher dans la liste'); ?>"> -->
				<!-- <div id="forms" class="panel-group">-->
					<div class="panel panel-default">
						<div class="panel-heading">
							<h5 class="panel-title">
									<i class="fa fa-shopping-cart"></i>
									<!-- <?php// echo $this->translate('Ajouter un produit'); ?> -->
									<?php echo $this->translate('Ajouter une ligne'); ?>
							</h5>
						</div>
						<div id="new-product-body"> 
							<div class="panel-body tiny-form">
								<?php echo $this->render('affaire/formulaireligneaffaire'); ?>
							</div>
						</div>
					</div>
					<!-- <div class="panel panel-default">
						<div class="panel-heading">
							<h5 class="panel-title">
								<a href="#new-previsionnel-body" id="new-previsionnel" data-parent="#forms" data-toggle="collapse">
									<i class="fa fa-calendar"></i>
									<?php echo $this->translate('Ajouter un prévisionnel heure'); ?>
								</a>
							</h5>
						</div>
						<div id="new-previsionnel-body" class="panel-collapse collapse">
							<div class="panel-body">
								Hello
							</div>
						</div>
					</div>
					<div class="panel panel-default">
						<div class="panel-heading">
							<h5 class="panel-title">
								<a href="#new-imprevu-body" id="new-imprevu" data-parent="#forms" data-toggle="collapse">
									<i class="fa fa-bell-slash-o"></i>
									<?php echo $this->translate('Ajouter un imprévu'); ?>
								</a>
							</h5>
						</div>
						<div id="new-imprevu-body" class="panel-collapse collapse">
							<div class="panel-body">
								Hello
							</div>
						</div>
					</div>
				</div> -->
			</div>
		</div>	

		<!-- formulaire d'ajout de ligne affaire ici -->

		<hr>

		<!-- Lignes affaire existantes ici -->
		
		
	</div>
	
	<div class="col-lg-12">
		<h3><?php echo $this->translate('Liste des produits'); ?></h3>					
		<div class="table-responsive">
			<table id="table-ligne" class="table table-striped">
			    <thead>
			        <th class="reference_produit"><?php echo $this->translate('Ref. produit'); ?></th>
			        <th class="intitule_produit"><?php echo $this->translate('Intitulé'); ?></th>
			        <th class="metier"><?php echo $this->translate('Métier'); ?></th>
			        <th class="charge"><?php echo $this->translate('Charge'); ?></th>
			        <th class="bool quantite"><?php echo $this->translate('Qté'); ?></th>
			        <th class="bool poids_unitaire" title="<?php echo $this->translate('Poids unitaire'); ?>"><?php echo $this->translate('PU').'*'; ?></th>
			        <th class="bool prix_unitaire_achat" title="<?php echo $this->translate('Prix unitaire achat'); ?>"><?php echo $this->translate('PUA').'*'; ?></th>
			        <th class="bool prix_unitaire_vente" title="<?php echo $this->translate('Prix unitaire vente'); ?>"><?php echo $this->translate('PUV').'*'; ?></th>
			        <th class="bool poids_total" title="<?php echo $this->translate('Poids total'); ?>"><?php echo $this->translate('PT').'*'; ?></th>
			        <th class="bool prix_total_achat" title="<?php echo $this->translate('Prix total achat'); ?>"><?php echo $this->translate('PTA').'*'; ?></th>
			        <th class="bool prix_total_vente" title="<?php echo $this->translate('Prix total vente'); ?>"><?php echo $this->translate('PTV').'*'; ?></th>
			    	
					
					<!-- Détails ligne -->
			    	<!-- <th data-hide="all"><?php echo $this->translate('Ref. devis'); ?></th>
			    	<th data-hide="all"><?php echo $this->translate('État achat'); ?></th>
			        <th data-hide="all"><?php echo $this->translate('État vente'); ?></th> -->
					
					<!-- Actions -->
			        <th class="bool actions">#</th>
			    </thead>
			    <tbody>
			        <!-- Début lignes tableau -->
			        <tr class="footable-visible">
			        	

						<!-- Ref. produit -->
			        	<td class="reference_produit">
			        		<span class="fa fa-angle-right"></span>
			        		20187491
			        	</td>

						<!-- Intitulé produit -->
			        	<td class="important-text intitule_produit">Cartouche filtrante 2.5m²</td>

			        	<!-- Métier -->
			        	<td class="metier">Matériel autres-fournisseurs</td>
	
						<!-- Charge -->
			        	<td class="charge">
			        		<a href="#" title="Consulter la commande fournisseur">
			        			<i class="fa fa-file-o"></i>
			        		</a>
			        		Externe
			        	</td>

						<!-- Quantité -->
			        	<td class="bool quantite">12</td>

						<!-- Poids unitaire -->
			        	<td class="bool poids_unitaire">0.00 kg</td>

						<!-- Prix unitaire achat -->
			        	<td class="bool prix_unitaire_achat">0.00 €</td>

						<!-- Prix unitaire vente -->
			        	<td class="bool prix_unitaire_vente">121.94 €</td>

						<!-- Poids total -->
			        	<td class="bool poids_total">0.00 kg</td>
						Prix total achat
			        	<td class="bool prix_total_achat">0.00 €</td>

						<!-- Prix total vente -->
			        	<td class="bool prix_total_vente">1463.28 €</td>

			        	<!-- # -->
			        	<td style="width:3%" class="bool actions">
			        		<a class="delete-ligne" href="#"><i class="fa fa-times"></i></a>
			        		<a class="edit-ligne" href="#"><i class="fa fa-edit"></i></a>
				        </td>
			        </tr>
			        <tr class="footable-row-detail">
			        	<td class="footable-row-detail-cell" colspan="12">
			        		<div class="footable-row-detail-inner">
			        			<div class="footable-row-detail-row hidden-lg">
			        				<div class="footable-row-detail-name"><?php echo $this->translate('Charge'); ?></div>
			        				<div class="footable-row-detail-value">
			        					<a href="#" title="Consulter la commande fournisseur">
						        			<i class="fa fa-file-o"></i>
						        		</a>
						        		Externe
			        				</div>
			        			</div>
			        			<div class="footable-row-detail-row">
			        				<div class="footable-row-detail-name"><?php echo $this->translate('Ref. devis'); ?></div>
			        				<div class="footable-row-detail-value"></div>
			        			</div>
			        			<div class="footable-row-detail-row">
			        				<div class="footable-row-detail-name"><?php echo $this->translate('État achat'); ?></div>
			        				<div class="footable-row-detail-value">Non commandé</div>
			        			</div>
			        			<div class="footable-row-detail-row">
			        				<div class="footable-row-detail-name"><?php echo $this->translate('État vente'); ?></div>
			        				<div class="footable-row-detail-value">Non livré</div>
			        			</div>
			        			<div class="footable-row-detail-row hidden-lg">
			        				<div class="footable-row-detail-name">#</div>
			        				<div class="footable-row-detail-value">
			        					<a class="btn btn-white btn-xs edit-ligne-hidden" href="#"><i class="fa fa-edit"></i> <?php echo $this->translate('Modifier'); ?></a>
			        					<a class="btn btn-danger btn-xs delete-ligne-hidden" href="#"><i class="fa fa-times"></i> <?php echo $this->translate('Supprimer'); ?></a>
			        				</div>
			        			</div>
			        		</div>
			        	</td>
			        </tr>
			        <tr class="footable-visible">
						<!-- Ref. produit -->
			        	<td>
			        		<span class="fa fa-angle-right"></span>
			        		20203950
			        	</td>

						<!-- Intitulé produit -->
			        	<td class="important-text">Poche filtrante D0610*1520</td>

			        	<!-- Métier -->
			        	<td>Matériel autres-fournisseurs</td>
	
						<!-- Charge -->
			        	<td>
			        		<a href="#" title="Consulter la commande fournisseur">
			        			<i class="fa fa-file-o"></i>
			        		</a>
			        		Externe
			        	</td>

			        	<!-- Quantité -->
			        	<td class="bool">10</td>

						<!-- Poids unitaire -->
			        	<td class="bool">0.00 kg</td>

						<!-- Prix unitaire achat -->
			        	<td class="bool">0.00 €</td>

						<!-- Prix unitaire vente -->
			        	<td class="bool">54.60 €</td>

			        	<!-- Poids total -->
			        	<td class="bool">0.00 kg</td>

						<!-- Prix total achat -->
			        	<td class="bool">0.00 €</td>

						<!-- Prix total vente -->
			        	<td class="bool">546.00 €</td>

			        	<!-- # -->
			        	<td style="width:3%" class="bool">
			        		<a class="delete-ligne" href="#"><i class="fa fa-times"></i></a>
			        		<a class="edit-ligne" href="#"><i class="fa fa-edit"></i></a>
				        </td>
			        </tr>
					<tr class="footable-row-detail">
			        	<td class="footable-row-detail-cell" colspan="12">
			        		<div class="footable-row-detail-inner">
			        			<div class="footable-row-detail-row hidden-lg">
			        				<div class="footable-row-detail-name"><?php echo $this->translate('Charge'); ?></div>
			        				<div class="footable-row-detail-value">
			        					<a href="#" title="Consulter la commande fournisseur">
						        			<i class="fa fa-file-o"></i>
						        		</a>
						        		Externe
			        				</div>
			        			</div>
			        			<div class="footable-row-detail-row">
			        				<div class="footable-row-detail-name"><?php echo $this->translate('Ref. devis'); ?></div>
			        				<div class="footable-row-detail-value"></div>
			        			</div>
			        			<div class="footable-row-detail-row">
			        				<div class="footable-row-detail-name"><?php echo $this->translate('État achat'); ?></div>
			        				<div class="footable-row-detail-value">Non commandé</div>
			        			</div>
			        			<div class="footable-row-detail-row">
			        				<div class="footable-row-detail-name"><?php echo $this->translate('État vente'); ?></div>
			        				<div class="footable-row-detail-value">Non livré</div>
			        			</div>
			        			<div class="footable-row-detail-row hidden-lg">
			        				<div class="footable-row-detail-name">#</div>
			        				<div class="footable-row-detail-value">
			        					<a class="btn btn-white btn-xs edit-ligne-hidden" href="#"><i class="fa fa-edit"></i> <?php echo $this->translate('Modifier'); ?></a>
			        					<a class="btn btn-danger btn-xs delete-ligne-hidden" href="#"><i class="fa fa-times"></i> <?php echo $this->translate('Supprimer'); ?></a>
			        				</div>
			        			</div>
			        		</div>
			        	</td>
			        </tr>
			    </tbody>
			    <tfoot>
			    	<tr>
			    		<th>Total vente/Total achat hors port</th>
			    	</tr>
			    </tfoot>
			</table>
		</div>
	</div>
</div>