<!-- module\Personnel\view\modal\formulairepassword.phtml -->

<form id="password-form" action="#" class="form-horizontal">
	<div class="form-group">
		<label for="ancien_mot_de_passe" class="col-lg-3 control-label">
			<?php echo $this->translate('Précédent'); ?>
		</label>
		<div class="col-lg-9">
			<input type="password" class="form-control" id="ancien_mot_de_passe" placeholder="<?php echo $this->translate('Ancien mot de passe'); ?>">
		</div>
	</div>
	<hr>
	<div class="form-group">
		<label for="mot_de_passe" class="col-lg-3 control-label">
			<?php echo $this->translate('Mot de passe'); ?>
		</label>
		<div class="col-lg-9">
			<input type="password" class="form-control" id="mot_de_passe" placeholder="<?php echo $this->translate('Mot de passe'); ?>">
		</div>
	</div>
	<div class="form-group">
		<label for="confirmation_mot_de_passe" class="col-lg-3 control-label">
			<?php echo $this->translate('Confirmation'); ?>
		</label>
		<div class="col-lg-9">
			<input type="password" class="form-control" id="confirmation_mot_de_passe" placeholder="<?php echo $this->translate('Confirmation'); ?>">
		</div>
	</div>
</form>