<!-- module\Personnel\view\personnel\index\profil.phtml -->

<?php
    use Zend\Session\Container;
    $utilisateurCourant = new Container('utilisateur');
    $admin = $utilisateurCourant->offsetGet('admin');
    $fonction = $utilisateurCourant->offsetGet('fonction');
?>

<div class="col-md-4 col-md-offset-4">
	<div id="cadre-profil" class="ibox-content">
		<section>
			<h3>
				<!-- <i class="fa fa-user"></i> -->
				<?php echo $utilisateurCourant->offsetGet('identite'); ?>
				<?php if($admin) : ?>
					(<?php echo $this->translate('Administrateur'); ?>)
				<?php endif; ?>
			</h3>

			<!-- <h4> <?php // echo $fonction; ?></h4> -->
			<p><i class="fa fa-clock-o"></i> <?php echo $utilisateurCourant->offsetGet('date_modif')->format('Y-m-d H:i:s'); ?></p>
			<p><i class="fa fa-envelope"></i> <a href="mailto:<?php echo $utilisateurCourant->offsetGet('email'); ?>"><?php echo $utilisateurCourant->offsetGet('email'); ?></a></p>
			<p><i class="fa fa-eur"></i> <?php echo ($utilisateurCourant->offsetGet('taux_horaire')) ? number_format($utilisateurCourant->offsetGet('taux_horaire'),2) : '&Oslash;' ?></p>

			<h4><?php echo $this->translate('Métiers'); ?></h4>
			<?php 
				if(isset($metiers)&&is_array($metiers)&&count($metiers)>0)
				{
					foreach($metiers as $metier)
					{
						echo $this->translate($metier).', ';
					}
				}
				else
				{
					echo $this->translate('Aucun métier trouvé.');
				}
			?>

		</section>

		<hr>

		<!-- <p>
			<a href="">
				<i class="fa fa-pencil"></i>
				<?php echo $this->translate('Éditer le profil'); ?>
			</a>
		</p> -->
		<p>			
			<a id="modifier-password" href="#">
				<i class="fa fa-key"></i>
				<?php echo $this->translate('Modifier le mot de passe'); ?>
			</a>
		</p>
	</div>
</div>


<div id="password-form-modal" class="modal inmodal in" aria-hidden="true" role="dialog" role="dialog" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button class="close" data-dismiss="modal" type="button">
					<span aria-hidden="true">×</span>
					<span class="sr-only"><?php echo $this->translate('Fermer'); ?></span>
				</button>
				<h4 class="modal-title"><?php echo $this->translate('Entrez le nouveau mot de passe'); ?></h4>
			</div>
			<div class="modal-body">
			</div>
			<div class="modal-footer">
				<button id="annuler" class="btn btn-white" data-dismiss="modal" type="button"><i class="fa fa-times"></i> <?php echo $this->translate('Annuler'); ?></button>
				<button id="password-form-submit" name="submit" class="btn btn-warning pull-right" type="button" data-default-text="<?php echo $this->translate('Modifier'); ?>" data-loading-text="<?php echo $this->translate('En cours...'); ?>">
					<i class="fa fa-trash"></i>
					<?php echo $this->translate('Modifier'); ?>
				</button>
			</div>
		</div>
	</div>
</div>