<!-- module\Fournisseur\view\fournisseur\index\listefournisseur.phtml -->

<div class="row">
	<div class="col-lg-12">
		<div class="panel">
			<div class="panel-heading">
				<div class="panel-options">
					<ul id="tabs" class="nav nav-tabs">
						<li role="presentation" id="tab-fournisseur" class="active">
							<a href="#fournisseurs" data-toggle="tab" aria-expanded="true">
								<i class="fa fa-list hidden-xs"></i>
								<?php echo $this->translate('Fournisseurs'); ?>
							</a>
						</li>
						<li role="presentation" id="tab-interlocuteur">
							<a href="#interlocuteurs" data-toggle="tab" aria-expanded="false">
								<i class="fa fa-user hidden-xs"></i>
								<?php echo $this->translate('Interlocuteurs'); ?>
							</a>
						</li>
					</ul>
				</div>
				<div class="panel-body">
					<div class="tab-content">
						<!-- Onglet fournisseur -->
						<div id="fournisseurs" class="tab-pane active">
							<div class="row">
                            	<a class="btn btn-primary btn-sm pull-right" href="<?php echo $this->url('formulaire_fournisseur'); ?>">
                            		<i class="fa fa-plus"></i>
                            		<?php echo $this->translate('Nouveau fournisseur') ?>
                            	</a>
                                <h3><?php echo $this->translate('Rechercher un fournisseur') ?></h3>
							</div>
							<hr>
							<div class="row">
								<div class="col-xs-12">
									<form action="" class="form-inline">
										<div class="form-group">
											<select id="activite-select" name="activite-select" class="chosen-select" multiple="" data-placeholder="<?php echo $this->translate('Par activité'); ?>">
												<!-- <option value=""><?php echo $this->translate('Activité'); ?></option> -->
												<?php foreach($this->activites as $activite) : ?>
													<option value="<?php echo $activite->getId(); ?>"><?php echo $this->translate($activite->getIntituleActivite()); ?></option>
												<?php endforeach; ?>
											</select>
										</div>
										<div class="form-group">
											<select id="categorie-select" name="categorie-select" class="chosen-select" multiple="" data-placeholder="<?php echo $this->translate('Par catégorie'); ?>">
												<!-- <option value=""><?php echo $this->translate('Catégorie'); ?></option> -->
												<?php foreach($this->categories as $categorie) : ?>
													<option value="<?php echo $categorie->getId(); ?>"><?php echo $this->translate($categorie->getIntituleCategorie()); ?></option>
												<?php endforeach; ?>
											</select>
										</div>
										<div class="form-group m-r-xs">
											<input id="mot_cle-input" name="search" placeholder="<?php echo $this->translate('Par mot clé'); ?>" type="search" class="form-control input-sm" aria-controls="table-fournisseur">
										</div>
										<button id="search-fournisseur" class="btn btn-white" type="submit">
											<i class="fa fa-search"></i>
											<?php echo $this->translate('Rechercher'); ?>
										</button>
									</form>
								</div>
							</div>
							<hr>
							<div class="row">
								<div class="col-xs-12">
									<!-- <div class="form-group m-r-xs pull-right">
										<div class="input-group">
											<input id="search-fournisseur" name="search" placeholder="<?php echo $this->translate('Rechercher'); ?>" type="search" class="form-control input-sm" aria-controls="table-fournisseur">
											<span id="search-fournisseur-span" class="input-group-addon">
													<i class="fa fa-search"></i>
											</span>
										</div>
									</div> -->

									<button class="btn btn-white btn-sm pull-right hidden-xs" type="submit">
										<?php echo $this->translate('Exporter'); ?>
									</button>
									<div class="form-group m-r-xs pull-right">
										<input id="fournisseur-filter" name="fournisseur-filter" placeholder="<?php echo $this->translate('Filtrer les résultats affichés'); ?>" type="search" class="form-control input-sm" aria-controls="table-fournisseur">
									</div>

									<?php if(sizeof($this->fournisseurs)>0): ?>
									<table id="table-fournisseur" class="table table-bordered table-hover table-striped table-condensed dataTable">
										<thead>
											<tr>
												<th><?php echo $this->translate('Code fournisseur'); ?></th>
												<th><?php echo $this->translate('Raison sociale'); ?></th>
												<th><?php echo $this->translate('Code postale'); ?></th>
												<th><?php echo $this->translate('Ville'); ?></th>
												<th><?php echo $this->translate('Pays'); ?></th>
												<th class="actions"><?php echo $this->translate('Actions'); ?></th>
											</tr>
										</thead>
										<tfoot>
											<tr>
												<th><?php echo $this->translate('Code fournisseur'); ?></th>
												<th><?php echo $this->translate('Raison sociale'); ?></th>
												<th><?php echo $this->translate('Code postale'); ?></th>
												<th><?php echo $this->translate('Ville'); ?></th>
												<th><?php echo $this->translate('Pays'); ?></th>
												<th class="actions"><?php echo $this->translate('Actions'); ?></th>
											</tr>
										</tfoot>
										<tbody>
											<?php foreach($this->fournisseurs as $fournisseur): ?>
												<tr>
													<td><?php echo (isset($fournisseur['code_fournisseur']))?$fournisseur['code_fournisseur']:''; ?></td>
													<td><?php echo $fournisseur['raison_sociale']; ?></td>
													<td><?php echo (isset($fournisseur['code_postal']))?$fournisseur['code_postal']:''; ?></td>
													<td><?php echo (isset($fournisseur['ville']))?$fournisseur['ville']:''; ?></td>
													<td><?php echo (isset($fournisseur['pays']))?$fournisseur['pays']:''; ?></td>
													<td class="actions">
                                                        <a href="<?php echo $this->url('fournisseur/consulter_fournisseur',array('id'=>$fournisseur['id'])); ?>"><i class="fa fa-eye fa-lg"></i></a>
                                                        <a href="<?php echo $this->url('formulaire_fournisseur',array('id'=>$fournisseur['id'])); ?>"><i class="fa fa-pencil-square-o fa-lg"></i></a>
                                                        <a href="#" class="fournisseur-delete-toggle fournisseur" data-target="#fournisseur-delete-modal" data-action="delete" data-id="<?php echo $fournisseur['id']; ?>"><i class="fa fa-trash-o fa-lg"></i></a> 
                                                    </td>
												</tr>
											<?php endforeach; ?>
										</tbody>
									</table>
									<?php else: ?>
										<p><?php echo $this->translate('Aucune donnée n\'a été trouvée.'); ?></p>
									<?php endif; ?>
								</div>
							</div>
						</div>
						<!-- Onglet Interlocuteurs -->
						<div id="interlocuteurs" class="tab-pane">
							<div class="row">
								<button id="interlocuteur-button" class="btn btn-primary btn-sm pull-right interlocuteur">
									<i class="fa fa-plus"></i>
									<?php echo $this->translate('Nouvel interlocuteur') ?>
								</button>
                                <h3><?php echo $this->translate('Rechercher un interlocuteur') ?></h3>
							</div>
							<hr>
							<div class="row">
								<div class="col-xs-12">
									<div class="form-group m-r-xs pull-right">
										<div class="input-group">
											<input id="search-interlocuteur" name="search" placeholder="<?php echo $this->translate('Rechercher'); ?>" type="search" class="form-control input-sm" aria-controls="table-interlocuteur">
											<span id="search-interlocuteur-span" class="input-group-addon">
												<!--<button id="search-btn" class="btn btn-flat btn-sm" name="seach" type="submit">-->
													<i class="fa fa-search"></i>
												<!--</button>-->
											</span>
										</div>
									</div>
									<table id="table-interlocuteur" class="table table-bordered table-hover table-striped table-condensed dataTable">
										<thead>
											<tr>
												<th><?php echo $this->translate('Interlocuteur'); ?></th>
												<th><?php echo $this->translate('Code société'); ?></th>
												<th><?php echo $this->translate('Société'); ?></th>
												<th><?php echo $this->translate('Email'); ?></th>
												<th class="bool"><?php echo $this->translate('Outlook'); ?></th>
												<th class="actions"><?php echo $this->translate('Actions'); ?></th>
											</tr>
										</thead>
										<tfoot>
											<tr>
												<th><?php echo $this->translate('Interlocuteur'); ?></th>
												<th><?php echo $this->translate('Code société'); ?></th>
												<th><?php echo $this->translate('Société'); ?></th>
												<th><?php echo $this->translate('Email'); ?></th>
												<th><?php echo $this->translate('Outlook'); ?></th>
												<th class="actions"><?php echo $this->translate('Actions'); ?></th>
											</tr>
										</tfoot>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="interlocuteur-modal" class="modal inmodal in" aria-hidden="true" role="dialog" role="dialog" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content animated bounceInRight">
		</div>
	</div>
</div>

<?php
	echo $this->render('fournisseur/overlay_formulaire_interlocuteur');
	echo $this->render('fournisseur/suppression_fournisseur'); // Modal de confirmation suppression fournisseur
	echo $this->render('fournisseur/suppression_interlocuteur'); // Modal de confirmation suppression interlocuteur
?>