<div class="row">
    <div class="col-lg-12">
        <div class="text-center m-t-lg">
            <h1>
                <!--Welcome in INSPINIA Static SeedProject-->
                Bienvenue sur Sigma V2.0
            </h1>
            <small>
                <!--It is an application skeleton for a typical web app. You can use it to quickly bootstrap your webapp projects and dev environment for these projects.-->
                Application de gestion commerciale de Zeppelin Systems France.
            </small>
        </div>
    </div>
</div>